PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../../../l4re-snapshot-23.10.1/src/l4

TARGET		= allocation_and_pkru
SRC_CC		= main.cc
SRC_S		= pkru_control.S ../../../../test_programs/testingMPK/cpuid.S

include $(L4DIR)/mk/prog.mk
